//! Obsidian Second Brain Integration
//! 
//! Sync memory entries to Obsidian vault
//! Extracted from claw-code/rust/crates/runtime/src/obsidian.rs

use std::path::{Path, PathBuf};
use serde::{Serialize, Deserialize};
use chrono::{DateTime, Utc};
use tokio::fs;

/// Memory entry for Second Brain
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryEntry {
    pub id: String,
    pub title: String,
    pub content: String,
    pub source: String,
    pub timestamp: DateTime<Utc>,
    pub importance: String,
    pub tags: Vec<String>,
}

impl MemoryEntry {
    /// Create new memory entry
    pub fn new(id: &str, title: &str, content: &str) -> Self {
        Self {
            id: id.to_string(),
            title: title.to_string(),
            content: content.to_string(),
            source: "unknown".to_string(),
            timestamp: Utc::now(),
            importance: "reference".to_string(),
            tags: Vec::new(),
        }
    }
    
    /// Set source
    pub fn with_source(mut self, source: &str) -> Self {
        self.source = source.to_string();
        self
    }
    
    /// Set importance
    pub fn with_importance(mut self, importance: &str) -> Self {
        self.importance = importance.to_string();
        self
    }
    
    /// Add tags
    pub fn with_tags(mut self, tags: Vec<String>) -> Self {
        self.tags = tags;
        self
    }
}

/// Obsidian vault sync
pub struct ObsidianSync {
    vault_path: PathBuf,
    inbox_path: PathBuf,
}

impl ObsidianSync {
    /// Create new Obsidian sync
    pub fn new(vault_path: impl AsRef<Path>) -> Self {
        let vault = vault_path.as_ref().to_path_buf();
        let inbox = vault.join("Inbox");
        Self {
            vault_path: vault,
            inbox_path: inbox,
        }
    }
    
    /// Initialize vault structure
    pub async fn initialize(&self) -> Result<(), std::io::Error> {
        fs::create_dir_all(&self.inbox_path).await
    }
    
    /// Sync entry to inbox
    pub async fn sync_to_inbox(
        &self,
        entry: &MemoryEntry,
    ) -> Result<PathBuf, std::io::Error> {
        let filename = format!("{}.md", sanitize_filename(&entry.title));
        let filepath = self.inbox_path.join(&filename);
        
        let content = format_obsidian_note(entry);
        fs::write(&filepath, content).await?;
        
        Ok(filepath)
    }
    
    /// Get vault path
    pub fn vault_path(&self) -> &Path {
        &self.vault_path
    }
}

/// Format memory entry as Obsidian note
fn format_obsidian_note(entry: &MemoryEntry) -> String {
    let tags_str = entry.tags
        .iter()
        .map(|t| format!("#{} ", t))
        .collect::<String>();
    
    format!(
        "# {}\n\n\
        **Source:** {}\n\
        **Timestamp:** {}\n\
        **Importance:** {}\n\
        **ID:** {}\n\n\
        {}\n\n\
        ---\n\n\
        ## Tags\n{}\n\n\
        *Auto-generated by OpenClaw*\n",
        entry.title,
        entry.source,
        entry.timestamp.format("%Y-%m-%d %H:%M:%S UTC"),
        entry.importance,
        entry.id,
        entry.content,
        tags_str
    )
}

/// Sanitize filename for filesystem
fn sanitize_filename(title: &str) -> String {
    let mut result = title.to_lowercase()
        .replace(" ", "-")
        .replace(|c: char| !c.is_alphanumeric() && c != '-', "")
        .trim_matches('-')
        .to_string();
    
    // Collapse multiple consecutive dashes into one
    while result.contains("--") {
        result = result.replace("--", "-");
    }
    
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_memory_entry_creation() {
        let entry = MemoryEntry::new("1", "Test Title", "Test content")
            .with_importance("critical")
            .with_tags(vec!["test".to_string(), "claw".to_string()]);
        
        assert_eq!(entry.id, "1");
        assert_eq!(entry.title, "Test Title");
        assert_eq!(entry.content, "Test content");
        assert_eq!(entry.importance, "critical");
        assert_eq!(entry.tags.len(), 2);
    }

    #[test]
    fn test_sanitize_filename() {
        assert_eq!(sanitize_filename("Hello World"), "hello-world");
        assert_eq!(sanitize_filename("Test @#$ File"), "test-file");
        assert_eq!(sanitize_filename("Multiple   Spaces"), "multiple-spaces");
    }

    #[test]
    fn test_format_obsidian_note() {
        let entry = MemoryEntry::new("1", "Test", "Content")
            .with_importance("important")
            .with_tags(vec!["test".to_string()]);
        
        let formatted = format_obsidian_note(&entry);
        
        assert!(formatted.contains("# Test"));
        assert!(formatted.contains("**Source:**"));
        assert!(formatted.contains("**Importance:** important"));
        assert!(formatted.contains("Content"));
        assert!(formatted.contains("#test"));
    }
}
